version: '3'

services:
  nginx:
    container_name: codelytv-ddd-skeleton-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8030:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mysql:
    container_name: codelytv-php_ddd_skeleton-mooc-mysql
    image: mysql:8
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]

  php:
    container_name: codelytv-php_ddd_skeleton-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - mysql
