framework:
  test: true

wouterj_eloquent:
  driver:   mysql
  host:     '%env(MOOC_DATABASE_HOST)%'
  port:     '%env(MOOC_DATABASE_PORT)%'
  database: '%env(MOOC_DATABASE_NAME)%'
  username: '%env(MOOC_DATABASE_USER)%'
  password: '%env(MOOC_DATABASE_PASSWORD)%'
  prefix:   ~
  eloquent: ~

services:
  _defaults:
    autoconfigure: true
    autowire: true

  CodelyTv\Tests\:
    resource: '../../../../tests/src'

  CodelyTv\Shared\Domain\RandomNumberGenerator: '@CodelyTv\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator'

  CodelyTv\Tests\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [!tagged codely.database_connection]

