imports:
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_database.yaml }
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true


  CodelyTv\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  CodelyTv\Apps\Mooc\Backend\Command\:
    resource: '../src/Command'
    tags: ['console.command']

  CodelyTv\:
    resource: '../../../../src'

  CodelyTv\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
