framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  CodelyTv\Tests\:
    resource: '../../../../tests/src'

  CodelyTv\Shared\Domain\RandomNumberGenerator: '@CodelyTv\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator'
  CodelyTv\Shared\Domain\ClockInterface: '@CodelyTv\Tests\Shared\Infrastructure\Clock\StaticDatetimeClockGenerator'